### ISSUE TITLE
[BUG] Missing Pod Information from Container Labels

### ISSUE THREAD

**Issue by fjogeleit** [aquasecurity/tracee#1786]
## Prerequisites

- [ ] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [ ] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [x] Someone else should solve this.

## Bug description

This is how I'm executing tracee (cmdline):

I am using Kubernetes to run tracee as DaemonSet, I used the following configuration:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: tracee
    app.kubernetes.io/component: tracee
    app.kubernetes.io/part-of: tracee
  name: tracee
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tracee
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tracee
      name: tracee
    spec:
      containers:
      - name: tracee
        image: docker.io/aquasec/tracee:full-dev
        imagePullPolicy: Always
        args:
          - --output-template /tracee/templates/rawjson.tmpl
        env:
          - name: LIBBPFGO_OSRELEASE_FILE
            value: /etc/os-release-host
        securityContext:
          privileged: true
        volumeMounts:
        - name: etc-os-release
          mountPath: /etc/os-release-host
          readOnly: true
        - name: modules
          mountPath: /lib/modules
          readOnly: true
        - name: src
          mountPath: /usr/src
          readOnly: true
        - name: socket
          mountPath: /var/run/containerd
          readOnly: true
        resources:
          limits: {}
          requests:
            cpu: 350m
            memory: 50Mi
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
      - hostPath:
          path: /etc/os-release
        name: etc-os-release
      - hostPath:
          path: /usr/src
        name: src
      - hostPath:
          path: /lib/modules
        name: modules
      - hostPath:
          path: /run/k3s/containerd
        name: socket
```

Environment:
Kubernetes Distribution: k3s
Kubernetes Version: v1.23.3+k3s1
Container Runtime: containerD
ContainerD Version: v1.5.9-k3s1

What I tried:

Installed tracee with the configuration above. I mounted the containerd socket at the path mentioned in the code: https://github.com/aquasecurity/tracee/blob/main/cmd/tracee-ebpf/internal/flags/flags-containers.go#L17

I found that additional information could be get in debug mode but I was not able to enable debugging with the provided container image. I also found the `containers` flag to set the runtime and path manually but also this was not possible to configure.

Steps to reproduce the issue:

- Install tracee as DeamonSet
- Run a nginx via `kubectl run nginx --image nginx`
- Install and exec strace inside the nginx 
  - `kubectl exec -it nginx -- apt-get update`
  - `kubectl exec -it nginx -- apt-get install -y strace`
  - `kubectl exec -it nginx -- strace ls`

The produced Event JSON contains keys for podName, podNamespace and podUID but they are empty. I would expect that the information are available.

Example Event:

```json
{
  "Data": null,
  "Context": {
    "timestamp": 1653227866340306400,
    "processorId": 3,
    "processId": 485,
    "threadId": 485,
    "parentProcessId": 483,
    "hostProcessId": 2138888,
    "hostThreadId": 2138888,
    "hostParentProcessId": 2138886,
    "userId": 0,
    "mountNamespace": 4026534304,
    "pidNamespace": 4026534305,
    "processName": "strace",
    "hostName": "nginx",
    "containerId": "",
    "eventId": "101",
    "eventName": "ptrace",
    "argsNum": 4,
    "returnValue": 0,
    "stackAddresses": null,
    "args": [
      {
        "name": "request",
        "type": "string",
        "value": "PTRACE_TRACEME"
      },
      {
        "name": "pid",
        "type": "pid_t",
        "value": 0
      },
      {
        "name": "addr",
        "type": "void*",
        "value": "0x0"
      },
      {
        "name": "data",
        "type": "void*",
        "value": "0x0"
      }
    ]
  },
  "SigMetadata": {
    "ID": "TRC-2",
    "Version": "0.1.0",
    "Name": "Anti-Debugging",
    "Description": "Process uses anti-debugging technique to block debugger",
    "Tags": [
      "linux",
      "container"
    ],
    "Properties": {
      "MITRE ATT&CK": "Defense Evasion: Execution Guardrails",
      "Severity": 3
    }
  }
}
```

**Comment by yanivagman** [comment]
Hi @fjogeleit 
I see that in the provided json output containerid is empty, which probably means that tracee failed to get the containerid from the cgroup path. If there is no containerid, there is no way to get any other pod information from the container runtime, so the container runtime socket is irrelevant in that case.
Do you mind execing into the tracee container and look at /sys/fs/cgroup? If you can find a subpath in that directory with your other container id (even as a substring of a subdirectory), then we should try to figure out why tracee failed to get the container id from that path, otherwise, this might be related to cgroup namespace or to https://github.com/aquasecurity/tracee/issues/1338#issuecomment-1027955397

**Comment by yanivagman** [comment]
> I also have an example with containerID but also without pod information, I think this example was after I mounted the socket into the container.

The container id is extracted from the cgroup path, so I don't believe this is realted to the fact that you mounted the socket. Might be two bugs (failing to extract the container id, and failing to enrich the event with container and pod information).
I'll let @danielpacak continue from here as he was already checking this

**Comment by fjogeleit** [comment]
Okay, if you need help or if I can help with another test run, just let me know. I can repeat the my tests.

**Comment by danielpacak** [comment]
I can reproduce the problem reported by @fjogeleit . Actually it's a follow to the [discussion](https://aquasecurity.slack.com/archives/C02LK3U786L/p1653640326905579) we had in Tracee Slack channel. We may have pure configuration issue here or bug in code. I'll double check and keep you posted.

**Comment by NDStrahilevitz** [comment]
So after some investigation on my side, I believe this is because the cgroup paths created by your k8s flavors (k3s in your case) do not indicate the container runtime used. 

For example: I've tested this with microk8s, where the cgroup paths created are of this `/kubepods/besteffort/pod9fb49d1d-9175-4fc2-8875-a183b95e3670/9972d535adfe794df43d85ae91848263fba5be8bd63e4db1d511ae765e6aeb1a` form.
As such an unknown runtime is detected and no enrichment occurs. This is also what's (partially) probably causing #1789

I have PoC fix where for unknown runtimes enrichment will instead try to use whatever registered enrichers exists and return the first successful result. I will upload a PR for that soon which should solve this.

**Comment by fjogeleit** [comment]
@NDStrahilevitz thanks for the investigation and fix. There is still an issue I encounter. So it works when Tracee is running and I create a pod but if the pod (e.g. nginx) already exists and then I install tracee the Pod information is still missing.

So it looks like that it only works for pods created after tracee is installed.

**Comment by fjogeleit** [comment]
I am getting events for the previous and new nginx but the previous one has not all information:

Event from already existing pod:

```json
{
   "Data":null,
   "Context":{
      "timestamp":1654794451025381715,
      "processorId":3,
      "processId":345,
      "cgroupId":4295183210,
      "threadId":345,
      "parentProcessId":343,
      "hostProcessId":1906216,
      "hostThreadId":1906216,
      "hostParentProcessId":1906214,
      "userId":0,
      "mountNamespace":4026532756,
      "pidNamespace":4026532757,
      "processName":"strace",
      "hostName":"nginx-prev",
      "containerId":"",
      "containerImage":"",
      "containerName":"",
      "podName":"",
      "podNamespace":"",
      "podUID":"",
      "eventId":"101",
      "eventName":"ptrace",
      "argsNum":4,
      "returnValue":0,
      "stackAddresses":null,
      "args":[
         {
            "name":"request",
            "type":"string",
            "value":"PTRACE_TRACEME"
         },
         {
            "name":"pid",
            "type":"pid_t",
            "value":0
         },
         {
            "name":"addr",
            "type":"void*",
            "value":"0x0"
         },
         {
            "name":"data",
            "type":"void*",
            "value":"0x0"
         }
      ]
   },
   "SigMetadata":{
      "ID":"TRC-2",
      "Version":"0.1.0",
      "Name":"Anti-Debugging",
      "Description":"Process uses anti-debugging technique to block debugger",
      "Tags":[
         "linux",
         "container"
      ],
      "Properties":{
         "MITRE ATT\u0026CK":"Defense Evasion: Execution Guardrails",
         "Severity":3
      }
   }
}
```

Event from a Pod create while tracee was already running:

```json
{
   "Data":null,
   "Context":{
      "timestamp":1654794595357112806,
      "processorId":0,
      "processId":338,
      "cgroupId":4294977056,
      "threadId":338,
      "parentProcessId":336,
      "hostProcessId":2671869,
      "hostThreadId":2671869,
      "hostParentProcessId":2671867,
      "userId":0,
      "mountNamespace":4026533743,
      "pidNamespace":4026533744,
      "processName":"strace",
      "hostName":"nginx",
      "containerId":"f157749472a300d86ec688313185dc1a2cb7f30277be061bcb6b0b2468cf2ede",
      "containerImage":"docker.io/library/nginx:latest",
      "containerName":"nginx",
      "podName":"nginx",
      "podNamespace":"tracee",
      "podUID":"a17ed04c-a222-49b1-84a1-456aeb17d82a",
      "eventId":"101",
      "eventName":"ptrace",
      "argsNum":4,
      "returnValue":0,
      "stackAddresses":null,
      "args":[
         {
            "name":"request",
            "type":"string",
            "value":"PTRACE_TRACEME"
         },
         {
            "name":"pid",
            "type":"pid_t",
            "value":0
         },
         {
            "name":"addr",
            "type":"void*",
            "value":"0x0"
         },
         {
            "name":"data",
            "type":"void*",
            "value":"0x0"
         }
      ]
   },
   "SigMetadata":{
      "ID":"TRC-2",
      "Version":"0.1.0",
      "Name":"Anti-Debugging",
      "Description":"Process uses anti-debugging technique to block debugger",
      "Tags":[
         "linux",
         "container"
      ],
      "Properties":{
         "MITRE ATT\u0026CK":"Defense Evasion: Execution Guardrails",
         "Severity":3
      }
   }
}
```

Environment is still a K3S Cluster with ContainerD as runtime.

Tracee runs with the containerd socket as readonly mount.

**Comment by yanivagman** [comment]
@fjogeleit my previous comment is now relevant again:

> Hi @fjogeleit
> I see that in the provided json output containerid is empty, which probably means that tracee failed to get the containerid from the cgroup path. If there is no containerid, there is no way to get any other pod information from the container runtime, so the container runtime socket is irrelevant in that case.
> Do you mind execing into the tracee container and look at /sys/fs/cgroup? If you can find a subpath in that directory with your other container id (even as a substring of a subdirectory), then we should try to figure out why tracee failed to get the container id from that path, otherwise, this might be related to cgroup namespace or to [#1338 (comment)](https://github.com/aquasecurity/tracee/issues/1338#issuecomment-1027955397)
